version: '3.4'

services:
  mongosrvtwo:
    container_name: db
    restart: always
    ports:
      - 27017
  diary.web:
    container_name: diaryweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "LearningDiaryApiUrl=http://diaryapi"
    ports:
      - "8100:80"

  diary.api:
    container_name: diaryapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://db:27017"
    depends_on:
      - mongosrvtwo
    ports:
      - "8101:80"

