version: '3.4'

services:
  mongodb:
    image: mongo
  diary.web:
    image: ${DOCKER_REGISTRY-}diaryweb
    build:
      context: .
      dockerfile: Diary.Web/Dockerfile

  diary.api:
    image: ${DOCKER_REGISTRY-}diaryapi
    build:
      context: .
      dockerfile: Diary.API/Dockerfile

