apiVersion: apps/v1
kind: Deployment
metadata:
  name: diaryapi-deployment
  labels:
    app: diaryapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diaryapi
  template:
    metadata:
      labels:
        app: diaryapi
    spec:
      containers:
        - name: diaryapi
          image: mgabrys/diaryapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service 
metadata:
  name: diaryapi-service
spec:
  type: NodePort
  selector:
    app: diaryapi
  ports:
   - protocol: TCP
     port: 8101
     targetPort: 80
     nodePort: 31000